### PR TITLE
revised with emperor logos and tim videos - aspect ratio 16:9

### PR DESCRIPTION
**Pull request by kattekrab**

### CODE REVIEW

**Comment by kattekrab** [comment]
Should look kinda like this
screenshot from 2015-01-03 16 17 14

**Comment by mithro** [comment]
What is happening with the TimVideos logo there?

Donna, I shared some high quality TimVideos logos at the following [URL](https://drive.google.com/a/mithis.com/folderview?id=0B5VlNZ_Rvdw6ZC1mWlhYRE5yLUU&usp=sharing)

**Comment by kattekrab** [comment]
Awesome!  Thanks Tim.

Do you have an SVG version with graphic and text side by side, along the lines of the mangled one I made?  (and sorry about that, I do know better)

D.

**Comment by mithro** [comment]
Do you have access to Adobe Illustrator? If so, there should be a vector version at https://drive.google.com/a/mithis.com/file/d/0B5VlNZ_Rvdw6S3BadmZMWTFFb0U/view?usp=sharing - I really need to convert it to SVG when I find someone with access.

Otherwise there is a Gimp XCF file at https://drive.google.com/a/mithis.com/file/d/0B5VlNZ_Rvdw6MjY1bF9CZkRSYVE/view?usp=sharing (converted from https://drive.google.com/a/mithis.com/file/d/0B5VlNZ_Rvdw6dmlnS05QTUVxbTg/view?usp=sharing ).

The simplified version I used to do our t-shirts can be found at https://drive.google.com/a/mithis.com/file/d/0B5VlNZ_Rvdw6VjFnOTBobXRxSVU/view?usp=sharing

Are any of them useful?

**Comment by kattekrab** [comment]
Unfortunately, I don't have illustrator.  If you can get the AI saved as an EPS or PDF then inkscape can usually do something with it.  But AI is just no go.

So - I had a crack at trace bitmap with the png and jpg versions.

SVG attached... I've put grey lines in to show the baselines to help show the different alignments.  The graphic has come up pretty well, but the text is a bit off.  Do you know what the font is?  If it's available, I can redo this as a crisp SVG pretty easily.

Damn - github won't let me upload the SVG.  here's a screengrab.  I'll commit the SVG via git.
screenshot from 2015-01-04 01 43 35


D.

**Comment by mithro** [comment]
First one looks the best to me. Fonts are at https://drive.google.com/a/mithis.com/folderview?id=0B5VlNZ_Rvdw6emxuMlZ6SVV3ZEE&usp=sharing

**Pull request merged**
