### PR TITLE
Adding an SVG of the TimVideos logos for review

### PR DESCRIPTION
**Pull request by kattekrab**

### CODE REVIEW

**Comment by kattekrab** [comment]
Tim sent through fonts - so I've created a new SVG of tims logo, and put that into the title slide.  Ryan/Carl - hope you don't mind me reversing out NDV - the blue in tim's videos didn't have enough contrast.  Also increased the font size for the speaker, and realigned everything.  

So... let's see!  Screenshots for easy review.

lca-titleslide

timsvideos-inline

**Comment by mithro** [comment]
LGTM. Carl has gone to bed now and will review tomorrow morning.

**Comment by kattekrab** [comment]
Cool. 

Via mobile.

**Comment by xfxf** [comment]
Hey Donna, looks great, thankyou.  We'll test this with both 576i and 720p encodes but it looks like it will scale well.

**Pull request merged**
